name: Docker Image CI

on:
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      
    - name: Build the Docker image
      run: docker build Mycontainer --file Mycontainer/Dockerfile --tag danielkiskutya/webrobbe:latest

    - name: Login to Dockehub
      run: docker login -p ${{ secrets.DOCKERHUB }}
      
    - name: Push to Dockerhub
      run: docker push danielkiskutya/webrobbe:latest
