name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Mycontainer/Dockerfile --tag danielkiskutya/webrobbe:latest

    - name: Push to Dockerhub
      run: docker push danielkiskutya/webrobbe:latest
